SCRIPT_LABELS = {
    "Latn": "Latin",
    "Cyrl": "Cyrillic",
    "Arab": "Arabic",
    "Deva": "Devanagari",
    "Hans": "Chinese (Simplified)",
    "Hant": "Chinese (Traditional)",
    "Jpan": "Japanese",
    "Hang": "Hangul (Korean)",
    "Beng": "Bengali",
    "Taml": "Tamil",
    "Telu": "Telugu",
    "Knda": "Kannada",
    "Mlym": "Malayalam",
    "Gujr": "Gujarati",
    "Guru": "Gurmukhi",
    "Orya": "Odia",
    "Sinh": "Sinhala",
    "Tibt": "Tibetan",
    "Thai": "Thai",
    "Khmr": "Khmer",
    "Mymr": "Myanmar/Burmese",
    "Geor": "Georgian",
    "Armn": "Armenian",
    "Hebr": "Hebrew",
    "Grek": "Greek",
    "Ethi": "Ethiopic",
    "Tfng": "Tifinagh",
    "Nkoo": "N'Ko",
    "Olck": "Ol Chiki",
    "Mtei": "Meitei Mayek",
    "Laoo": "Lao",
}

SCRIPT_COLORS = {
    "Latin": "#1f77b4",
    "Cyrillic": "#ff7f0e",
    "Arabic": "#2ca02c",
    "Devanagari": "#d62728",
    "Chinese (Simplified)": "#9467bd",
    "Chinese (Traditional)": "#8c564b",
    "Japanese": "#e377c2",
    "Hangul (Korean)": "#7f7f7f",
    "Bengali": "#bcbd22",
    "Tamil": "#17becf",
    "Telugu": "#aec7e8",
    "Kannada": "#ffbb78",
    "Malayalam": "#98df8a",
    "Gujarati": "#ff9896",
    "Gurmukhi": "#c5b0d5",
    "Odia": "#c49c94",
    "Sinhala": "#f7b6d2",
    "Tibetan": "#c7c7c7",
    "Thai": "#dbdb8d",
    "Khmer": "#9edae5",
    "Myanmar/Burmese": "#393b79",
    "Georgian": "#5254a3",
    "Armenian": "#637939",
    "Hebrew": "#8ca252",
    "Greek": "#e7ba52",
    "Ethiopic": "#bd9e39",
    "Tifinagh": "#ad494a",
    "N'Ko": "#8c6d31",
    "Ol Chiki": "#843c39",
    "Meitei Mayek": "#7b4173",
    "Lao": "#5254a3",
}